### ISSUE TITLE
Glitches in gound truth uzh_tracking_area_run2_imu.txt

### ISSUE THREAD

**Issue by zerolover** [hemi86/hiltislamchallenge#15]
![image](https://user-images.githubusercontent.com/4061122/134531258-88696361-63b5-4e18-8eb7-839e65180745.png)
As someone pointed out before, see https://github.com/hemi86/hiltislamchallenge/issues/3#issuecomment-918826725
The outliers still existed and the RMSE was large...
Please fix it, Thanks

**Comment by hemi86** [comment]
Hi @zerolover I just uploaded a fixed version.
