### ISSUE TITLE
Final evaluation procedure

### ISSUE THREAD

**Issue by smauq** [hemi86/hiltislamchallenge#17]
I have two questions about how the final evaluations will go.
- First of all, I realized I put a different email title ("Hilti SLAM Challenge submission") than the suggested one ("[HILTI SLAM Challenge]"). I hope this doesn't make a difference.
- Are we informed of the results beforehand, or everyone finds out during the workshop? Just wondering how this goes along with what's written that "Submissions are not automatically published – you can review the results and decide whether to publish by yourself."

**Comment by hemi86** [comment]
1) the subject does not make a difference
2) I am currently preparing the email with the results for all participants - stay tuned :)
