### ISSUE TITLE
Groundtruth dead links

### ISSUE THREAD

**Issue by yhabib29** [hemi86/hiltislamchallenge#19]
Hello,
Few scene groundtruth are not available, links are not valid:
- [IC_Office_1_pole.txt](https://storage.googleapis.com/hilti_challenge/IC_Office_1_pole.txt)
- [[Office_Mitte_1_pole.txt](https://storage.googleapis.com/hilti_challenge/Office_Mitte_1_pole.txt)
- [Parking_1_pole.txt](https://storage.googleapis.com/hilti_challenge/Parking_1_pole.txt)
- [Basement_3_prism.txt](https://storage.googleapis.com/hilti_challenge/Basement_3_prism.txt)
- [Construction_Site_1_prism.txt](https://storage.googleapis.com/hilti_challenge/Construction_Site_1_prism.txt)
- [Campus_1_prism.txt](https://storage.googleapis.com/hilti_challenge/Campus_1_prism.txt)

Can you upload them again ?

**Comment by EnochPer** [comment]
Hello, I meet the same question, the download links of these groundtruth are not valid. If you get these groundtruth, would you contact me? my email: 1016001513@qq.com. Thank you!

**Comment by zerolover** [comment]
[GroundTruthHilti2021.tar.gz](https://github.com/hemi86/hiltislamchallenge/files/8397090/GroundTruthHilti2021.tar.gz)

**Comment by hilti-challenge** [comment]
I would also like to encourage you to use our [automatic evaluation system](https://submit.hilti-challenge.com/)!

**Comment by EnochPer** [comment]
Thank you so much!




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月1日(星期五) 晚上7:12
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [hemi86/hiltislamchallenge] Groundtruth dead links (Issue #19)





 
GroundTruthHilti2021.tar.gz

**Comment by yhabib29** [comment]
Thank you !
