### ISSUE TITLE
Cam0 Image upside down

### ISSUE THREAD

**Issue by dwindy** [hemi86/hiltislamchallenge#22]
Hi there,

Firstly I would like to thank you for publishing this dataset.
I'm testing my work in it. Because I'm not using ROS so I extracted the image/LiDAR data from the ROS bag.

It seems like the cam0 and cam4 images are flip, upside down.
I checked the RPG Drone Testing Arena sequence and  basement1 sequence.
Below is the example image of 1 frame of Arena sequence, in the order of cam0, cam1, cam2, cam3, cam4.

regards
 
![1630577757386802673](https://user-images.githubusercontent.com/11047587/226235533-b1288fbb-92bc-495a-95fc-6a1f79800f5f.png)

![1630577757386802673](https://user-images.githubusercontent.com/11047587/226235556-6405e30b-617d-4d93-b789-3f614772507e.png)

![1630577757386802673](https://user-images.githubusercontent.com/11047587/226235570-f6e8b7d0-6d54-4d55-8fae-0621c6f45dfe.png)

![1630577757386802673](https://user-images.githubusercontent.com/11047587/226235607-57be24d1-9a03-4801-b032-a30415d68f0f.png)

![1630577757386802673](https://user-images.githubusercontent.com/11047587/226235627-160043d7-cfac-4b80-8d51-b68461d928d3.png)

**Comment by hilti-challenge** [comment]
Yes that is correct, one image of the stereo pair is upside down. This enabled a symmetric hardware design of the camera head.

**Comment by dwindy** [comment]
> 

Understood
Thank you.

**Comment by dwindy** [comment]
> Yes that is correct, one image of the stereo pair is upside down. This enabled a symmetric hardware design of the camera head.

Understood
Thank you.
