### ISSUE TITLE
Suggestion: extra datasets with static initial condition.

### ISSUE THREAD

**Issue by brytsknguyen** [hemi86/hiltislamchallenge#5]
Dear Hilti team,

Thanks for the interesting dataset. 

I notice that you start recording the datasets from a non-static state. This makes initialization of visual inertial or lidar inertial methods difficult (is it intentional?). I have tried vins-fusion and VIRAL SLAM with all datasets and they both quickly destabilized, regardless of the IMU used. It could be because the proper IMU noise parameters have not been set yet. But to tune this properly we should also emilinate the uncertainty in non-static starting state.

So if it is possible I suggest you record an extra sequence where the pole is kept static (maybe add a base like our rig below, or just use some weights to keep it static) before starting recording and moving the setup.

![base](https://user-images.githubusercontent.com/13504903/131533589-47beba8b-9216-4ef2-a22b-f784c423ba87.jpeg)

We also have published a multi-lidar, multi-camera, multi-imu dataset recently (https://ntu-aris.github.io/ntu_viral_dataset/sensors_and_usage.html). I hope we can exchange some experience.

Regards

**Comment by hemi86** [comment]
Thanks for your suggestions - we will add additional datasets where the pole will be kept static in the beginning.

**Comment by hemi86** [comment]
We now added 2 additional datasets with static initial conditions: [RPG Tracking Area](https://storage.googleapis.com/hilti_challenge/uzh_tracking_area_run2.bag) (incl. 6DOF ground truth) and [Basement_3](https://storage.googleapis.com/hilti_challenge/Basement_3.bag) and [Basement_4](https://storage.googleapis.com/hilti_challenge/Basement_4.bag). Let me know what you think!

Thank you for sharing your datasets!

**Comment by mauricefallon** [comment]
I noticed you are using the OS0-64 lidar from ouster. This has a functioning upper range of about 25m (advertised at 50m).
Was this intentional.

This means that for some sequences (Parking, Campus) the sensor is deprived of measurements.
Using other lidars on the market Ouster OS1, Hesai and Velodyne all have 80 or 100m range. The Velodyne is used by KAARTA, GeoSLAM and Paracosm for example.

The difficulty of these sequences isnt the motion of the sensor, but rather the choice of sensor.

**Comment by hemi86** [comment]
Yes we are aware of this limitation of the Ouster OS0. Algorithms that additionally use the information from cameras will have an advantage in these sequences.
