### ISSUE TITLE
Skipping data during recording

### ISSUE THREAD

**Issue by JanQuenzel** [hemi86/hiltislamchallenge#6]
Hey there,

I saw in rqt_bag that for LAB_Survey_2.bag multiple times up to 1 second of recording is missing.
Also some messages are crammed together ( rqt_bag shows them at recording time rather than header->stamp ), checking the timestamps and sequence IDs e.g. for /os_cloud_node/points shows that quite some messages are missing.
In case you also recorded the /os_node/lidar_packets  there might be a way to recover the messages at least partially.

I haven't checked, but this might concern other bags as well.

Changing the rosbag buffer size during recording might prevent similar issues in the future.

Best, Jan

**Comment by hemi86** [comment]
Hi Jan, thanks for noticing! Indeed sometimes the load on the controller was too high causing some frame drops. Unfortunately we did not record the lidar_packets.

Best
Michael
